### ISSUE TITLE
Add a more graceful error message when dependencies are not installed for input/get script

### ISSUE THREAD

**Issue by dridon** [Sable/Ostrich2#66]
Error: Expand input-file: Execution error for /home/faiz/dev/Ostrich2/benchmarks/lud/input/get 8 1337:
    at Object.macros./experiment/input-file (/usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:346:13)
    at Object.macros./definitions/expandable-reference (/usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:388:38)
    at /usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:470:44
    at traverse (/usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:487:17)
    at traverse (/usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:482:9)
    at traverse (/usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:482:9)
    at traverse (/usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:482:9)
    at Object.exports.expand (/usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:500:3)
    at /usr/lib/node_modules/wu-wei-benchmarking-toolkit/lib/config.js:905:15
    at Array.forEach (native)

**Comment by elavoie** [comment]
This is caused by a missing dependency (scipy and numpy).  Changed the issue title to turn it into an actionable thing.
